
// Import local modules
import '@modules/mobile-nav'
import '@modules/lazyload'
import '@modules/show-hide'
import '@modules/header'
import '@modules/form-validating'
import '@modules/load-posts'
import '@modules/slider'
import '@modules/faqs-accordion'
import '@modules/modals'
import '@modules/vacancy-filters'
import '@modules/submenu'
import '@modules/expression-interest'
import '@modules/course-cta-header'
import '@modules/course-apply-validation'
import '@modules/stripe'
import '@modules/course-directory-tabs'
import '@modules/course-grid-slider'
